spring:
  application:
    file:
      uploads:
        photos-output-path: .\uploads
  profiles:
    active: dev
  mail:
    host: host
    port: port
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 3MB
springdoc:
  default-produces-media-type: application/json
