spring:
  security:
    jwt:
      secret-key: your-secret-key
      expiration: 600000 # 10 min
      refresh-token:
        expiration: 604800000 # 7 days
  datasource:
    url: jdbc:postgresql://localhost:5432/hms_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
